name: flownet2
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - absl-py=0.9.0=py37hc8dfbb8_1
  - blas=1.0=mkl
  - blinker=1.4=py_1
  - brotlipy=0.7.0=py37h8f50634_1000
  - c-ares=1.16.1=h516909a_0
  - ca-certificates=2020.6.24=0
  - cachetools=4.1.1=py_0
  - certifi=2020.6.20=py37_0
  - cffi=1.14.0=py37he30daa8_1
  - chardet=3.0.4=py37hc8dfbb8_1006
  - click=7.1.2=pyh9f0ad1d_0
  - cloudpickle=1.5.0=py_0
  - colorama=0.4.3=py_0
  - cryptography=3.0=py37hb09aad4_0
  - cuda92=1.0=0
  - cudatoolkit=10.0.130=0
  - cycler=0.10.0=py37_0
  - cytoolz=0.10.1=py37h7b6447c_0
  - dask-core=2.20.0=py_0
  - dbus=1.13.16=hb2f20db_0
  - decorator=4.4.2=py_0
  - expat=2.2.9=he6710b0_2
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.10.2=h5ab3b9f_0
  - glib=2.65.0=h3eb4bd4_0
  - google-auth=1.20.0=py_0
  - google-auth-oauthlib=0.4.1=py_2
  - grpcio=1.30.0=py37hb0870dc_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb31296c_0
  - icu=58.2=he6710b0_3
  - idna=2.10=pyh9f0ad1d_0
  - imageio=2.9.0=py_0
  - importlib-metadata=1.7.0=py37hc8dfbb8_0
  - intel-openmp=2020.1=217
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.2.0=py37hfd86e86_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.12.4=h8b12597_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=he19cac6_1
  - lz4-c=1.9.2=he6710b0_1
  - markdown=3.2.2=py_0
  - matplotlib=3.2.2=0
  - matplotlib-base=3.2.2=py37hef1b27d_0
  - mkl=2020.1=217
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.1.0=py37h23d657b_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - ncurses=6.2=he6710b0_1
  - networkx=2.4=py_1
  - ninja=1.10.0=py37hfd86e86_0
  - numpy=1.19.1=py37hbc911f0_0
  - numpy-base=1.19.1=py37hfa32c7d_0
  - oauthlib=3.0.1=py_0
  - olefile=0.46=py37_0
  - openssl=1.1.1g=h7b6447c_0
  - pcre=8.44=he6710b0_0
  - pillow=7.2.0=py37hb39fc2d_0
  - pip=20.1.1=py37_1
  - protobuf=3.12.4=py37h3340039_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=py_2
  - pyjwt=1.7.1=py_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py37h05f1152_2
  - pysocks=1.7.1=py37hc8dfbb8_1
  - python=3.7.7=hcff3b4d_5
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytorch=1.0.1=py3.7_cuda10.0.130_cudnn7.4.2_2
  - pytz=2020.1=py_0
  - pywavelets=1.1.1=py37h7b6447c_0
  - pyyaml=5.3.1=py37h7b6447c_1
  - qt=5.9.7=h5867ecd_1
  - readline=8.0=h7b6447c_0
  - requests=2.24.0=pyh9f0ad1d_0
  - requests-oauthlib=1.3.0=pyh9f0ad1d_0
  - rsa=4.6=pyh9f0ad1d_0
  - scikit-image=0.16.2=py37h0573a6f_0
  - scipy=1.2.1=py37h7c811a0_0
  - setproctitle=1.1.10=py37h7b6447c_1001
  - setuptools=49.2.0=py37_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.15.0=py_0
  - sqlite=3.32.3=h62c20be_0
  - tensorboard=2.3.0=py_0
  - tensorboard-plugin-wit=1.6.0=pyh9f0ad1d_0
  - tensorboardx=2.1=py_0
  - tk=8.6.10=hbc83047_0
  - toolz=0.10.0=py_0
  - torchvision=0.2.2=py_3
  - tornado=6.0.4=py37h7b6447c_1
  - tqdm=4.47.0=py_0
  - urllib3=1.25.10=py_0
  - werkzeug=1.0.1=pyh9f0ad1d_0
  - wheel=0.34.2=py37_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
